name: Compilar Diapositivas
on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del c√≥digo
        uses: actions/checkout@v4

      - name: Compilar todos los archivos .tex
        uses: xu-cheng/latex-action@v3
        with:
          root_file: "*.tex"
          work_in_root_file_dir: true
          compiler: pdflatex

      - name: Subir PDFs generados
        uses: actions/upload-artifact@v4
        with:
          name: diapositivas-pdf
          path: "**/*.pdf"