name: Compilar Diapositivas
on:
  push:
    tags:
      - 'v*'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del c√≥digo
        uses: actions/checkout@v4

      - name: Compilar todos los archivos .tex
        uses: xu-cheng/latex-action@v3
        with:
          root_file: "*.tex"
          work_in_root_file_dir: true
          compiler: pdflatex

      - name: Preparar PDFs para release
        run: |
          mkdir -p release
          find . -name "*.pdf" -exec cp {} release/ \;

      - name: Crear Release con PDFs
        uses: softprops/action-gh-release@v2
        with:
          files: release/*.pdf
          generate_release_notes: true